services:
  - type: web
    name: next-js
    env: node
    plan: starter
    buildCommand: next start
    startCommand: next build
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_BASE_URL
        value: soon